# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MicroLife',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_factor', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[(b'F', b'female'), (b'M', b'male'), (b'O', b'prefer not to say')], max_length=40)),
                ('valence', models.DecimalField(decimal_places=2, max_digits=5)),
                ('source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[(b'F', b'female'), (b'M', b'male'), (b'O', b'prefer not to say')], max_length=40)),
                ('birthday', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='exposure',
            name='microlife',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microlives.MicroLife'),
        ),
        migrations.AddField(
            model_name='exposure',
            name='siteuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microlives.SiteUser'),
        ),
    ]
